set -g mouse on

# remap prefix from 'C-b' to 'C-z'
unbind C-z
set-option -g prefix C-z
bind-key C-z send-prefix

set -g default-terminal "screen-256color"

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# arrow keys to move between next and prev window
bind -n C-Left select-window -t -
bind -n C-Right select-window -t +
unbind n
unbind p

# emacs keybindings for windows
bind C-n new-window
unbind c
bind C-k kill-window
unbind &

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

set -g mouse on