#!/bin/bash

set -a; source "$(dirname "${BASH_SOURCE[0]}")/../.env"; set +a
export PYTHONPATH=$PYTHONPATH:$PWD
# export HF_HOME="/scratch/general/vast/u1419632/"

# module load cuda/12.9.0
# module load gcc/11.2.0
